

version: '3'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: quality_smiles_backend_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db/quality_smiles_backend_development
    volumes:
      - .:/rails
    depends_on:
      - db

volumes:
  postgres_data: